"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Events = void 0;
var Events;
(function (Events) {
    Events["DEBUG"] = "debug";
    Events["READY"] = "ready";
    Events["MESSAGE_CREATE"] = "message";
    Events["MESSAGE_UPDATE"] = "messageUpdate";
    Events["MESSAGE_REACTION_ADD"] = "reaction";
    Events["MESSAGE_REACTION_REMOVE"] = "reactionRemove";
    Events["CONNECT"] = "connect";
    Events["DISCONNECT"] = "disconnect";
    Events["SHARD_READY"] = "shardReady";
    Events["GUILD_CREATE"] = "guildCreate";
    Events["GUILD_DELETE"] = "guildDelete";
    Events["GUILD_UPDATE"] = "guildUpdate";
    Events["GUILD_BAN_ADD"] = "guildBan";
    Events["GUILD_BAN_REMOVE"] = "guildBanRemove";
    Events["HELLO"] = "hello";
    Events["INTERACTION_CREATE"] = "interaction";
    Events["VOICE_STATE_UPDATE"] = "voiceStateUpdate";
    Events["GUILD_MEMBER_UPDATE"] = "memberUpdate";
    Events["GUILD_MEMBER_ADD"] = "memberAdd";
    Events["GUILD_MEMBER_REMOVE"] = "memberRemove";
    Events["GUILD_ROLE_CREATE"] = "roleCreate";
    Events["GUILD_ROLE_UPDATE"] = "roleUpdate";
    Events["GUILD_ROLE_DELETE"] = "roleDelete";
    Events["MESSAGE_DELETE"] = "messageDelete";
    Events["MESSAGE_DELETE_BULK"] = "messageBulkDelete";
    Events["MESSAGE_REACTION_REMOVE_ALL"] = "reactionRemoveAll";
    Events["MESSAGE_REACTION_REMOVE_EMOJI"] = "reactionRemoveEmoji";
    Events["TYPING_START"] = "typing";
})(Events = exports.Events || (exports.Events = {}));
