import Bot from './src/Bot';
import * as Constants from './src/constants/Constants';
import Collection from './src/collection/Collection';
import BitField from './src/util/BitField';
import Role from './src/structures/Role';
import Member from './src/structures/Member';
import User from './src/structures/User';
import Resolve from './src/util/Resolve';
import Embed from './src/structures/Embed';
import Message from './src/structures/Message';
import Guild from './src/structures/Guild';
import TextChannel from './src/structures/channels/TextChannel';
import Emoji from './src/structures/Emoji';
import BaseChannel from './src/structures/channels/BaseChannel';
import GuildChannel from './src/structures/channels/GuildChannel';
import Shard from './src/gateway/Shard';
import ShardManager from './src/gateway/ShardManager';
import DMChannel from './src/structures/channels/DMChannel';
import CacheManager from './src/managers/CacheManager';
import WebSocket from './src/ws/WebSocket';
import Rest from './src/rest/RestAPI';
import Reaction from './src/structures/Reaction';
import Command from './src/structures/command/Command';
import CommandContext from './src/structures/command/CommandContext';
import BotUser from './src/BotUser';
import Button from './src/structures/Button';
import Components from './src/structures/Components';
import SelectMenu from './src/structures/SelectMenu';
declare const _default: {
    Bot: typeof Bot;
    WebSocket: typeof WebSocket;
    Constants: typeof Constants;
    Intents: {
        GUILDS: number;
        GUILD_MEMBERS: number;
        GUILD_BANS: number;
        GUILD_EMOJIS: number;
        GUILD_INTEGRATIONS: number;
        GUILD_WEBHOOKS: number;
        GUILD_INVITES: number;
        GUILD_VOICE_STATES: number;
        GUILD_PRESENCES: number;
        GUILD_MESSAGES: number;
        GUILD_MESSAGE_REACTIONS: number;
        GUILD_MESSAGE_TYPING: number;
        DIRECT_MESSAGES: number;
        DIRECT_MESSAGE_REACTIONS: number;
        DIRECT_MESSAGE_TYPING: number;
        ALL: number;
    };
    Collection: typeof Collection;
    BitField: typeof BitField;
    Role: typeof Role;
    Member: typeof Member;
    User: typeof User;
    Resolve: typeof Resolve;
    Embed: typeof Embed;
    Message: typeof Message;
    Guild: typeof Guild;
    TextChannel: typeof TextChannel;
    BaseChannel: typeof BaseChannel;
    GuildChannel: typeof GuildChannel;
    DMChannel: typeof DMChannel;
    Emoji: typeof Emoji;
    Shard: typeof Shard;
    ShardManager: typeof ShardManager;
    CacheManager: typeof CacheManager;
    Rest: typeof Rest;
    Reaction: typeof Reaction;
    Command: typeof Command;
    CommandContext: typeof CommandContext;
    BotUser: typeof BotUser;
    Format: {
        createTimestamp: (time: number) => string;
        createStyledTimestamp: (time: number, style: import("./src/types/Types").StyleTimestamp) => string;
        createUserMention: (userId: string) => string;
        createRoleMention: (roleId: string) => string;
        createChannelMention: (channelId: string) => string;
        createEmojiCode: (emojiName: string, emojiId: string) => string;
        createAnimatedEmojiCode: (emojiName: string, emojiId: string) => string;
    };
    Button: typeof Button;
    Components: typeof Components;
    SelectMenu: typeof SelectMenu;
};
export default _default;
//# sourceMappingURL=index.d.ts.map