import Collection from '../collection/Collection';
import type Role from './Role';
import Member from './Member';
import type Emoji from './Emoji';
import GuildChannel from './channels/GuildChannel';
import type Bot from '../Bot';
import VoiceState from './VoiceState';
import { snowflake } from '../types/Types';
import Permissions from '../util/Permissions';
declare class Guild {
    private _id;
    private _bot;
    private _name;
    private _icon;
    private _description;
    private _splash;
    private _discoverySplash;
    private _features;
    private _banner;
    private _ownerId;
    private _applicationId;
    private _region;
    private _afkChannelId;
    private _afkTimeout;
    private _systemChannelId;
    private _widgetEnabled;
    private _widgetChannelId;
    private _verificationLevel;
    private _defaultMessageNotifications;
    private _mfaLevel;
    private _explicitContentFilter;
    private _maxPresences;
    private _maxMembers;
    private _maxVideoChannelUsers;
    private _vanityUrl;
    private _premiumTier;
    private _premiumSubscriptionCount;
    private _systemChannelFlags;
    private _preferredLocale;
    private _rulesChannelId;
    private _publicUpdatesChannelId;
    private _embedEnabled;
    private _embedChannelId;
    private _stickers;
    private _nsfw_level;
    private _memberCount;
    private _presenceCount;
    private _roles;
    private _members;
    private _emojis;
    private _channels;
    private _voiceStates;
    constructor(_id: string, _bot: Bot, _name: string, _icon: string, _description: string, _splash: string, _discoverySplash: string, _features: any[], _banner: string, _ownerId: string, _applicationId: string, _region: string, _afkChannelId: string, _afkTimeout: string, _systemChannelId: string, _widgetEnabled: boolean, _widgetChannelId: string, _verificationLevel: number, _defaultMessageNotifications: number, _mfaLevel: number, _explicitContentFilter: number, _maxPresences: number, _maxMembers: number, _maxVideoChannelUsers: number, _vanityUrl: string, _premiumTier: number, _premiumSubscriptionCount: number, _systemChannelFlags: number, _preferredLocale: string, _rulesChannelId: string, _publicUpdatesChannelId: string, _embedEnabled: boolean, _embedChannelId: string, _stickers: any[], _nsfw_level: number, _memberCount: number, _presenceCount: number);
    get shard(): import("../gateway/Shard").default | undefined;
    get roles(): Collection<string, Role>;
    set roles(roles: Collection<string, Role>);
    get emojis(): Collection<string, Emoji>;
    set emojis(emojis: Collection<string, Emoji>);
    get channels(): Collection<string, GuildChannel>;
    set channels(channels: Collection<string, GuildChannel>);
    get name(): string;
    get defaultMessageNotifications(): number;
    get members(): Collection<string, Member>;
    get systemChannelFlags(): number;
    get region(): string;
    set members(members: Collection<string, Member>);
    get id(): string;
    get icon(): string;
    get verificationLevel(): number;
    get vanityUrl(): string;
    get description(): string;
    get splash(): string;
    get maxMambers(): number;
    get nsfwLevel(): number;
    get afkTimeout(): string;
    get maxPresences(): number;
    get presenceCount(): number;
    get banner(): string;
    get discoverySplash(): string;
    get explicitContentFilter(): number;
    get mfaLevel(): number;
    get stickers(): any[];
    get boosterSubscriptionCount(): number;
    get boosterTier(): number;
    get applicationId(): string;
    get memberCount(): number;
    get bot(): Bot;
    get rulesChannelId(): string;
    get features(): any[];
    get voiceStates(): Collection<string, VoiceState>;
    get ownerId(): snowflake;
    permissionsOf(member: snowflake | Member): Permissions;
    get owner(): Member | undefined;
    rulesChannel(): Promise<GuildChannel>;
}
export default Guild;
//# sourceMappingURL=Guild.d.ts.map